### ISSUE TITLE
@LTLengthOf problem associated with passing multiple string as arguments.

### ISSUE THREAD

**Issue by ovshake** [kelloggm/checker-framework#141]
For the following code (when multiple strings are passed as shown in the manual)

```
import org.checkerframework.checker.index.qual.*;

class IndexTest{
	public static void main(String[] args) {
		String firstName = "abhishek";
		String lastName = "maiti";
		@LTLengthOf("firstName", "lastName") int index;
		index = 1;
		
	}
}

```
the following error is shown

```
IndexTest.java:7: error: annotation values must be of the form 'name=value'
                @LTLengthOf("firstName", "lastName") int index;
                            ^
IndexTest.java:7: error: annotation values must be of the form 'name=value'
                @LTLengthOf("firstName", "lastName") int index;
                                         ^
IndexTest.java:7: error: annotation @LTLengthOf is missing a default value for the element 'value'
                @LTLengthOf("firstName", "lastName") int index;
                ^
3 errors

```
But it works fine when both the strings are passed individually.

**Comment by mernst** [comment]
Your code contains a syntax error:  it code is invalid Java and doesn't even compile with the regular javac (without running the Index Checker).

Instead of writing 

```java
		@LTLengthOf("firstName", "lastName") int index;
```

you need to write

```java
		@LTLengthOf({"firstName", "lastName"}) int index;
```

The javac error message is a bit obscure, but that's what it is trying to say.  I have explained this in commit f5579e5.

There were also some missing curly braces in the Index Checker manual, which might have led you to the incorrect syntax.  Sorry about that!  I corrected this in commit dce36065f8ba673c94b7a5b299c1fd51efd72bb8.

**Comment by ovshake** [comment]
thanks!
